### ISSUE TITLE
Newer build of VS now working as expected?

### ISSUE THREAD

**Issue by coatsy** [OfficeDev/office-docs#78] opened 2016-03-21 06:52 UTC
Module Number: O3652-2
Module Title: Deep-dive into Office Word Add-ins
Path of file: ./lab.md
Part 1, step 12.
The button text was updated for me - is this a transient bug, or can we update the image in step 11 and the text in step 12?

**Comment by LezaMax** [comment] 2016-03-28 19:05
I'm closing this one as I added those steps. The bug reproduces if developers hit F5 before updating the text because the code will cache the add-in so any further updates won't be reflected. The text should remain as such

**Closed by LezaMax** 2016-03-28 19:05 UTC
